### ISSUE TITLE
 NoMethodError when rendering a template with partial directly with Tilt

### ISSUE THREAD

**Issue by mourad-ifeelgoods** [jamesotron/FlavourSaver#18]
It can be reproduced with the following example in rails console 

``` ruby
FS.register_partial(:my_partial, 'I am a partial')

template = Tilt['handlebars'].new { '{{foo}} {{> my_partial}}' }
data = OpenStruct.new foo: 'Hello'

template.render(data)
```

It should output the string "Hello I am a partial", but it fail with this error

```
NoMethodError: undefined method `render' for #<OpenStruct foo="hello">
        from /flavour_saver-0.3.3/lib/flavour_saver/runtime.rb:107:in `evaluate_partial'
        from /flavour_saver-0.3.3/lib/flavour_saver/runtime.rb:88:in `evaluate_node'
        from /flavour_saver-0.3.3/lib/flavour_saver/runtime.rb:61:in `block in evaluate_node'
        from /flavour_saver-0.3.3/lib/flavour_saver/runtime.rb:61:in `map'
        from /flavour_saver-0.3.3/lib/flavour_saver/runtime.rb:61:in `evaluate_node'
        from /flavour_saver-0.3.3/lib/flavour_saver/runtime.rb:37:in `to_s'
        from /flavour_saver-0.3.3/lib/flavour_saver/runtime.rb:14:in `run'
        from /flavour_saver-0.3.3/lib/flavour_saver/template.rb:15:in `evaluate'
        from /tilt-1.4.1/lib
```

**Comment by jcreamer898** [comment]
@jamesotron He's not seeing the "No need to register partials inside Rails." error.

I'm actually wrestling with a similar issue right now with `#each`.

**Comment by jcreamer898** [comment]
I'm seeing the same error in this scenario...

```ruby
module ApplicationHelper
  def images
    [
      OpenStruct.new({ src: "/foo.jpg" }), 
      OpenStruct.new({ src: "/bar.jpg" }), 
      OpenStruct.new({ src: "/baz.jpg" })
    ].map(&OpenStruct.method(:new))
  end
end
```

```html
{{#each images}}
  {{> image}}
{{/each}}
```
