### ISSUE TITLE
Lexer does not accept identifier with an underscore prefix (e.g. `_3`)

### ISSUE THREAD

**Issue by andrewhao** [jamesotron/FlavourSaver#32]
If I'm reading the [lexer source](https://github.com/wycats/handlebars.js/blob/master/src/handlebars.l) on the Handlebars library correctly, identifiers may utilize the underscore `_` character.

[The documentation also states](http://handlebarsjs.com/expressions.html): 
```Identifiers may be any unicode character except for the following: Whitespace ! " # % & ' ( ) * + , . / ; < = > @ [ \ ] ^ ` { | } ~```

However, I am unable to use an underscore in FlavourSaver:

```
>> Tilt['handlebars'].new { '{{_3}}' }
RLTK::LexingError: Unable to match string with any of the given rules:
        from /opt/boxen/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rltk-2.2.1/lib/rltk/lexer.rb:141:in `lex'
        from /opt/boxen/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/flavour_saver-0.3.6/lib/flavour_saver/template.rb:11:in `prepare'
        from /opt/boxen/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/tilt-1.4.1/lib/tilt/template.rb:79:in `initialize'
        from (irb):4:in `new'
        from (irb):4
        from /opt/boxen/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/commands/console.rb:110:in `start'
        from /opt/boxen/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/commands/console.rb:9:in `start'
        from /opt/boxen/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:68:in `console'
        from /opt/boxen/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /opt/boxen/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
>> Tilt['handlebars'].new { '{{_3}}' }
RLTK::LexingError: Unable to match string with any of the given rules:
        from /opt/boxen/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rltk-2.2.1/lib/rltk/lexer.rb:141:in `lex'
        from /opt/boxen/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/flavour_saver-0.3.6/lib/flavour_saver/template.rb:11:in `prepare'
        from /opt/boxen/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/tilt-1.4.1/lib/tilt/template.rb:79:in `initialize'
        from (irb):5:in `new'
        from (irb):5
        from /opt/boxen/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/commands/console.rb:110:in `start'
        from /opt/boxen/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/commands/console.rb:9:in `start'
        from /opt/boxen/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:68:in `console'
        from /opt/boxen/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /opt/boxen/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
```

**Comment by andrewhao** [comment]
👍
